name: ci
on: [push]
jobs:
  Test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --global npm@6
      - run: npm ci
      - run: npm test
