name: Test
on: [push]
jobs:
  #
  # Tests
  #
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global npm@8
      - run: npm ci
      - run: npm test
